import type { IconTileVariants } from '@aezakmiproject/hesoyam'
import type { Component } from 'vue'
import {
  ALargeSmall,
  AlignLeft,
  AppWindow,
  Award,
  Bell,
  BookOpen,
  Boxes,
  Building2,
  Calendar,
  ChevronRight,
  ChevronsDownUp,
  ChevronsLeftRight,
  ChevronsUpDown,
  CircleAlert,
  CircleDot,
  CircleUser,
  Code,
  Columns2,
  Copy,
  CreditCard,
  Download,
  Ellipsis,
  FolderTree,
  Gauge,
  Grid3x3,
  Inbox,
  Keyboard,
  Layers,
  ListChecks,
  ListFilter,
  Loader,
  LoaderCircle,
  Megaphone,
  Menu,
  MessageCircle,
  Minus,
  MoreHorizontal,
  MoveHorizontal,
  MousePointerClick,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelRight,
  PanelsTopLeft,
  RectangleHorizontal,
  ScrollText,
  Search,
  Shapes,
  SlidersHorizontal,
  Smile,
  Sparkles,
  SquareCheck,
  SquareMousePointer,
  StickyNote,
  SunMoon,
  Table2,
  Tag,
  Terminal,
  TextCursorInput,
  TextSelect,
  ToggleLeft,
  ToggleRight,
  Video,
} from '@lucide/vue'

export type NavChipTone = NonNullable<IconTileVariants['variant']>

export interface NavChip {
  icon: Component
  variant: NavChipTone
}

export const navChipFallback: NavChip = {
  icon: Sparkles,
  variant: 'gray',
}

export const navChipByHref: Record<string, NavChip> = {
  '/': { icon: BookOpen, variant: 'blue' },
  '/installation': { icon: Download, variant: 'green' },
  '/colors': { icon: Palette, variant: 'pink' },
  '/typography': { icon: ALargeSmall, variant: 'gray' },
  '/materials': { icon: Layers, variant: 'purple' },
  '/blocks': { icon: Boxes, variant: 'teal' },
  '/icons': { icon: Smile, variant: 'amber' },

  '/avatar': { icon: CircleUser, variant: 'blue' },
  '/badge': { icon: Award, variant: 'green' },
  '/banner': { icon: Megaphone, variant: 'purple' },
  '/breadcrumbs': { icon: ChevronRight, variant: 'gray' },
  '/button': { icon: SquareMousePointer, variant: 'blue' },
  '/calendar': { icon: Calendar, variant: 'red' },
  '/checkbox': { icon: SquareCheck, variant: 'green' },
  '/code-block': { icon: Code, variant: 'gray' },
  '/collapse': { icon: ChevronsDownUp, variant: 'teal' },
  '/combobox': { icon: ChevronsUpDown, variant: 'purple' },
  '/context-card': { icon: CreditCard, variant: 'blue' },
  '/context-menu': { icon: MousePointerClick, variant: 'pink' },
  '/copy-button': { icon: Copy, variant: 'amber' },
  '/drawer': { icon: PanelBottom, variant: 'gray' },
  '/empty-state': { icon: Inbox, variant: 'purple' },
  '/entity': { icon: Building2, variant: 'teal' },
  '/error': { icon: CircleAlert, variant: 'red' },
  '/fieldset': { icon: TextSelect, variant: 'blue' },
  '/file-tree': { icon: FolderTree, variant: 'amber' },
  '/gauge': { icon: Gauge, variant: 'green' },
  '/grid': { icon: Grid3x3, variant: 'gray' },
  '/icon-tile': { icon: Shapes, variant: 'purple' },
  '/input': { icon: TextCursorInput, variant: 'blue' },
  '/keyboard-input': { icon: Keyboard, variant: 'purple' },
  '/label': { icon: Tag, variant: 'pink' },
  '/loading-dots': { icon: Ellipsis, variant: 'teal' },
  '/marquee': { icon: MoveHorizontal, variant: 'teal' },
  '/menu': { icon: Menu, variant: 'gray' },
  '/modal': { icon: AppWindow, variant: 'blue' },
  '/multi-select': { icon: ListChecks, variant: 'green' },
  '/note': { icon: StickyNote, variant: 'amber' },
  '/pagination': { icon: ChevronsLeftRight, variant: 'purple' },
  '/progress': { icon: Loader, variant: 'teal' },
  '/radio': { icon: CircleDot, variant: 'blue' },
  '/scroller': { icon: ScrollText, variant: 'gray' },
  '/search-input': { icon: Search, variant: 'pink' },
  '/select': { icon: ListFilter, variant: 'purple' },
  '/separator': { icon: Minus, variant: 'gray' },
  '/sheet': { icon: PanelRight, variant: 'blue' },
  '/show-more': { icon: MoreHorizontal, variant: 'teal' },
  '/sidebar': { icon: PanelLeft, variant: 'purple' },
  '/skeleton': { icon: RectangleHorizontal, variant: 'gray' },
  '/slider': { icon: SlidersHorizontal, variant: 'green' },
  '/snippet': { icon: Terminal, variant: 'purple' },
  '/spinner': { icon: LoaderCircle, variant: 'blue' },
  '/split-button': { icon: Columns2, variant: 'pink' },
  '/switch': { icon: ToggleLeft, variant: 'green' },
  '/table': { icon: Table2, variant: 'teal' },
  '/tabs': { icon: PanelsTopLeft, variant: 'blue' },
  '/textarea': { icon: AlignLeft, variant: 'gray' },
  '/theme-switcher': { icon: SunMoon, variant: 'amber' },
  '/toast': { icon: Bell, variant: 'red' },
  '/toggle': { icon: ToggleRight, variant: 'purple' },
  '/tooltip': { icon: MessageCircle, variant: 'blue' },
  '/video': { icon: Video, variant: 'pink' },

}

export function navChipFor(href: string): NavChip {
  return navChipByHref[href] ?? navChipFallback
}
